export {default} from './HomePage'
export { default as Banner } from './Banner/Banner'
export { default as Technologies } from './Technologies/Technologies'
export { default as Architecture } from './Architecture/Architecture'
export { default as NextMeetUp } from './NextMeetUp/NextMeetUp'